default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: two_plus_two_development

test:
  <<: *default
  database: two_plus_two_test

production:
  <<: *default
  host: localhost
  adapter: postgresql
  encoding: utf8
  database: two_plus_two_production
  pool: 5
  username: <%= ENV['TWO_PLUS_TWO_DATABASE_USER'] %>
  password: <%= ENV['TWO_PLUS_TWO_DATABASE_PASSWORD'] %>
